//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wsdot.Traffic
{
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Wsdot.Traffic.IHighwayCameras")]
    public interface IHighwayCameras
    {
        
        // CODEGEN: Parameter 'GetCamerasResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHighwayCameras/GetCameras", ReplyAction="http://tempuri.org/IHighwayCameras/GetCamerasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Wsdot.Traffic.GetCamerasResponse GetCameras(Wsdot.Traffic.GetCamerasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHighwayCameras/GetCameras", ReplyAction="http://tempuri.org/IHighwayCameras/GetCamerasResponse")]
        System.Threading.Tasks.Task<Wsdot.Traffic.GetCamerasResponse> GetCamerasAsync(Wsdot.Traffic.GetCamerasRequest request);
        
        // CODEGEN: Parameter 'GetCamerasAsDataSetResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHighwayCameras/GetCamerasAsDataSet", ReplyAction="http://tempuri.org/IHighwayCameras/GetCamerasAsDataSetResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Wsdot.Traffic.GetCamerasAsDataSetResponse GetCamerasAsDataSet(Wsdot.Traffic.GetCamerasAsDataSetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHighwayCameras/GetCamerasAsDataSet", ReplyAction="http://tempuri.org/IHighwayCameras/GetCamerasAsDataSetResponse")]
        System.Threading.Tasks.Task<Wsdot.Traffic.GetCamerasAsDataSetResponse> GetCamerasAsDataSetAsync(Wsdot.Traffic.GetCamerasAsDataSetRequest request);
        
        // CODEGEN: Parameter 'SearchCamerasResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHighwayCameras/SearchCameras", ReplyAction="http://tempuri.org/IHighwayCameras/SearchCamerasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Wsdot.Traffic.SearchCamerasResponse SearchCameras(Wsdot.Traffic.SearchCamerasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHighwayCameras/SearchCameras", ReplyAction="http://tempuri.org/IHighwayCameras/SearchCamerasResponse")]
        System.Threading.Tasks.Task<Wsdot.Traffic.SearchCamerasResponse> SearchCamerasAsync(Wsdot.Traffic.SearchCamerasRequest request);
        
        // CODEGEN: Parameter 'GetCameraResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHighwayCameras/GetCamera", ReplyAction="http://tempuri.org/IHighwayCameras/GetCameraResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Wsdot.Traffic.GetCameraResponse GetCamera(Wsdot.Traffic.GetCameraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHighwayCameras/GetCamera", ReplyAction="http://tempuri.org/IHighwayCameras/GetCameraResponse")]
        System.Threading.Tasks.Task<Wsdot.Traffic.GetCameraResponse> GetCameraAsync(Wsdot.Traffic.GetCameraRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class Camera
    {
        
        private int cameraIDField;
        
        private bool cameraIDFieldSpecified;
        
        private RoadwayLocation cameraLocationField;
        
        private string cameraOwnerField;
        
        private string descriptionField;
        
        private double displayLatitudeField;
        
        private bool displayLatitudeFieldSpecified;
        
        private double displayLongitudeField;
        
        private bool displayLongitudeFieldSpecified;
        
        private int imageHeightField;
        
        private bool imageHeightFieldSpecified;
        
        private string imageURLField;
        
        private int imageWidthField;
        
        private bool imageWidthFieldSpecified;
        
        private bool isActiveField;
        
        private bool isActiveFieldSpecified;
        
        private string ownerURLField;
        
        private string regionField;
        
        private int sortOrderField;
        
        private bool sortOrderFieldSpecified;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CameraID
        {
            get
            {
                return this.cameraIDField;
            }
            set
            {
                this.cameraIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CameraIDSpecified
        {
            get
            {
                return this.cameraIDFieldSpecified;
            }
            set
            {
                this.cameraIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public RoadwayLocation CameraLocation
        {
            get
            {
                return this.cameraLocationField;
            }
            set
            {
                this.cameraLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string CameraOwner
        {
            get
            {
                return this.cameraOwnerField;
            }
            set
            {
                this.cameraOwnerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double DisplayLatitude
        {
            get
            {
                return this.displayLatitudeField;
            }
            set
            {
                this.displayLatitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DisplayLatitudeSpecified
        {
            get
            {
                return this.displayLatitudeFieldSpecified;
            }
            set
            {
                this.displayLatitudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public double DisplayLongitude
        {
            get
            {
                return this.displayLongitudeField;
            }
            set
            {
                this.displayLongitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DisplayLongitudeSpecified
        {
            get
            {
                return this.displayLongitudeFieldSpecified;
            }
            set
            {
                this.displayLongitudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int ImageHeight
        {
            get
            {
                return this.imageHeightField;
            }
            set
            {
                this.imageHeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ImageHeightSpecified
        {
            get
            {
                return this.imageHeightFieldSpecified;
            }
            set
            {
                this.imageHeightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string ImageURL
        {
            get
            {
                return this.imageURLField;
            }
            set
            {
                this.imageURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int ImageWidth
        {
            get
            {
                return this.imageWidthField;
            }
            set
            {
                this.imageWidthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ImageWidthSpecified
        {
            get
            {
                return this.imageWidthFieldSpecified;
            }
            set
            {
                this.imageWidthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool IsActive
        {
            get
            {
                return this.isActiveField;
            }
            set
            {
                this.isActiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsActiveSpecified
        {
            get
            {
                return this.isActiveFieldSpecified;
            }
            set
            {
                this.isActiveFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string OwnerURL
        {
            get
            {
                return this.ownerURLField;
            }
            set
            {
                this.ownerURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string Region
        {
            get
            {
                return this.regionField;
            }
            set
            {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int SortOrder
        {
            get
            {
                return this.sortOrderField;
            }
            set
            {
                this.sortOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SortOrderSpecified
        {
            get
            {
                return this.sortOrderFieldSpecified;
            }
            set
            {
                this.sortOrderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class RoadwayLocation
    {
        
        private string descriptionField;
        
        private string directionField;
        
        private decimal latitudeField;
        
        private bool latitudeFieldSpecified;
        
        private decimal longitudeField;
        
        private bool longitudeFieldSpecified;
        
        private decimal milePostField;
        
        private bool milePostFieldSpecified;
        
        private string roadNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Direction
        {
            get
            {
                return this.directionField;
            }
            set
            {
                this.directionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal Latitude
        {
            get
            {
                return this.latitudeField;
            }
            set
            {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LatitudeSpecified
        {
            get
            {
                return this.latitudeFieldSpecified;
            }
            set
            {
                this.latitudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal Longitude
        {
            get
            {
                return this.longitudeField;
            }
            set
            {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LongitudeSpecified
        {
            get
            {
                return this.longitudeFieldSpecified;
            }
            set
            {
                this.longitudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal MilePost
        {
            get
            {
                return this.milePostField;
            }
            set
            {
                this.milePostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MilePostSpecified
        {
            get
            {
                return this.milePostFieldSpecified;
            }
            set
            {
                this.milePostFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string RoadName
        {
            get
            {
                return this.roadNameField;
            }
            set
            {
                this.roadNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCameras", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCamerasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AccessCode;
        
        public GetCamerasRequest()
        {
        }
        
        public GetCamerasRequest(string AccessCode)
        {
            this.AccessCode = AccessCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCamerasResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCamerasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
        public Wsdot.Traffic.Camera[] GetCamerasResult;
        
        public GetCamerasResponse()
        {
        }
        
        public GetCamerasResponse(Wsdot.Traffic.Camera[] GetCamerasResult)
        {
            this.GetCamerasResult = GetCamerasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCamerasAsDataSet", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCamerasAsDataSetRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AccessCode;
        
        public GetCamerasAsDataSetRequest()
        {
        }
        
        public GetCamerasAsDataSetRequest(string AccessCode)
        {
            this.AccessCode = AccessCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCamerasAsDataSetResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCamerasAsDataSetResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet GetCamerasAsDataSetResult;
        
        public GetCamerasAsDataSetResponse()
        {
        }
        
        public GetCamerasAsDataSetResponse(System.Data.DataSet GetCamerasAsDataSetResult)
        {
            this.GetCamerasAsDataSetResult = GetCamerasAsDataSetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchCameras", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SearchCamerasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AccessCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StateRoute;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Region;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> StartingMilepost;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> EndingMilepost;
        
        public SearchCamerasRequest()
        {
        }
        
        public SearchCamerasRequest(string AccessCode, string StateRoute, string Region, System.Nullable<double> StartingMilepost, System.Nullable<double> EndingMilepost)
        {
            this.AccessCode = AccessCode;
            this.StateRoute = StateRoute;
            this.Region = Region;
            this.StartingMilepost = StartingMilepost;
            this.EndingMilepost = EndingMilepost;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchCamerasResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SearchCamerasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
        public Wsdot.Traffic.Camera[] SearchCamerasResult;
        
        public SearchCamerasResponse()
        {
        }
        
        public SearchCamerasResponse(Wsdot.Traffic.Camera[] SearchCamerasResult)
        {
            this.SearchCamerasResult = SearchCamerasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCamera", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCameraRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AccessCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int CameraID;
        
        public GetCameraRequest()
        {
        }
        
        public GetCameraRequest(string AccessCode, int CameraID)
        {
            this.AccessCode = AccessCode;
            this.CameraID = CameraID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCameraResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCameraResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Wsdot.Traffic.Camera GetCameraResult;
        
        public GetCameraResponse()
        {
        }
        
        public GetCameraResponse(Wsdot.Traffic.Camera GetCameraResult)
        {
            this.GetCameraResult = GetCameraResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHighwayCamerasChannel : Wsdot.Traffic.IHighwayCameras, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HighwayCamerasClient : System.ServiceModel.ClientBase<Wsdot.Traffic.IHighwayCameras>, Wsdot.Traffic.IHighwayCameras
    {
        
        public HighwayCamerasClient()
        {
        }
        
        public HighwayCamerasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public HighwayCamerasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public HighwayCamerasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public HighwayCamerasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Wsdot.Traffic.GetCamerasResponse Wsdot.Traffic.IHighwayCameras.GetCameras(Wsdot.Traffic.GetCamerasRequest request)
        {
            return base.Channel.GetCameras(request);
        }
        
        public Wsdot.Traffic.Camera[] GetCameras(string AccessCode)
        {
            Wsdot.Traffic.GetCamerasRequest inValue = new Wsdot.Traffic.GetCamerasRequest();
            inValue.AccessCode = AccessCode;
            Wsdot.Traffic.GetCamerasResponse retVal = ((Wsdot.Traffic.IHighwayCameras)(this)).GetCameras(inValue);
            return retVal.GetCamerasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Wsdot.Traffic.GetCamerasResponse> Wsdot.Traffic.IHighwayCameras.GetCamerasAsync(Wsdot.Traffic.GetCamerasRequest request)
        {
            return base.Channel.GetCamerasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Wsdot.Traffic.GetCamerasResponse> GetCamerasAsync(string AccessCode)
        {
            Wsdot.Traffic.GetCamerasRequest inValue = new Wsdot.Traffic.GetCamerasRequest();
            inValue.AccessCode = AccessCode;
            return ((Wsdot.Traffic.IHighwayCameras)(this)).GetCamerasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Wsdot.Traffic.GetCamerasAsDataSetResponse Wsdot.Traffic.IHighwayCameras.GetCamerasAsDataSet(Wsdot.Traffic.GetCamerasAsDataSetRequest request)
        {
            return base.Channel.GetCamerasAsDataSet(request);
        }
        
        public System.Data.DataSet GetCamerasAsDataSet(string AccessCode)
        {
            Wsdot.Traffic.GetCamerasAsDataSetRequest inValue = new Wsdot.Traffic.GetCamerasAsDataSetRequest();
            inValue.AccessCode = AccessCode;
            Wsdot.Traffic.GetCamerasAsDataSetResponse retVal = ((Wsdot.Traffic.IHighwayCameras)(this)).GetCamerasAsDataSet(inValue);
            return retVal.GetCamerasAsDataSetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Wsdot.Traffic.GetCamerasAsDataSetResponse> Wsdot.Traffic.IHighwayCameras.GetCamerasAsDataSetAsync(Wsdot.Traffic.GetCamerasAsDataSetRequest request)
        {
            return base.Channel.GetCamerasAsDataSetAsync(request);
        }
        
        public System.Threading.Tasks.Task<Wsdot.Traffic.GetCamerasAsDataSetResponse> GetCamerasAsDataSetAsync(string AccessCode)
        {
            Wsdot.Traffic.GetCamerasAsDataSetRequest inValue = new Wsdot.Traffic.GetCamerasAsDataSetRequest();
            inValue.AccessCode = AccessCode;
            return ((Wsdot.Traffic.IHighwayCameras)(this)).GetCamerasAsDataSetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Wsdot.Traffic.SearchCamerasResponse Wsdot.Traffic.IHighwayCameras.SearchCameras(Wsdot.Traffic.SearchCamerasRequest request)
        {
            return base.Channel.SearchCameras(request);
        }
        
        public Wsdot.Traffic.Camera[] SearchCameras(string AccessCode, string StateRoute, string Region, System.Nullable<double> StartingMilepost, System.Nullable<double> EndingMilepost)
        {
            Wsdot.Traffic.SearchCamerasRequest inValue = new Wsdot.Traffic.SearchCamerasRequest();
            inValue.AccessCode = AccessCode;
            inValue.StateRoute = StateRoute;
            inValue.Region = Region;
            inValue.StartingMilepost = StartingMilepost;
            inValue.EndingMilepost = EndingMilepost;
            Wsdot.Traffic.SearchCamerasResponse retVal = ((Wsdot.Traffic.IHighwayCameras)(this)).SearchCameras(inValue);
            return retVal.SearchCamerasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Wsdot.Traffic.SearchCamerasResponse> Wsdot.Traffic.IHighwayCameras.SearchCamerasAsync(Wsdot.Traffic.SearchCamerasRequest request)
        {
            return base.Channel.SearchCamerasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Wsdot.Traffic.SearchCamerasResponse> SearchCamerasAsync(string AccessCode, string StateRoute, string Region, System.Nullable<double> StartingMilepost, System.Nullable<double> EndingMilepost)
        {
            Wsdot.Traffic.SearchCamerasRequest inValue = new Wsdot.Traffic.SearchCamerasRequest();
            inValue.AccessCode = AccessCode;
            inValue.StateRoute = StateRoute;
            inValue.Region = Region;
            inValue.StartingMilepost = StartingMilepost;
            inValue.EndingMilepost = EndingMilepost;
            return ((Wsdot.Traffic.IHighwayCameras)(this)).SearchCamerasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Wsdot.Traffic.GetCameraResponse Wsdot.Traffic.IHighwayCameras.GetCamera(Wsdot.Traffic.GetCameraRequest request)
        {
            return base.Channel.GetCamera(request);
        }
        
        public Wsdot.Traffic.Camera GetCamera(string AccessCode, int CameraID)
        {
            Wsdot.Traffic.GetCameraRequest inValue = new Wsdot.Traffic.GetCameraRequest();
            inValue.AccessCode = AccessCode;
            inValue.CameraID = CameraID;
            Wsdot.Traffic.GetCameraResponse retVal = ((Wsdot.Traffic.IHighwayCameras)(this)).GetCamera(inValue);
            return retVal.GetCameraResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Wsdot.Traffic.GetCameraResponse> Wsdot.Traffic.IHighwayCameras.GetCameraAsync(Wsdot.Traffic.GetCameraRequest request)
        {
            return base.Channel.GetCameraAsync(request);
        }
        
        public System.Threading.Tasks.Task<Wsdot.Traffic.GetCameraResponse> GetCameraAsync(string AccessCode, int CameraID)
        {
            Wsdot.Traffic.GetCameraRequest inValue = new Wsdot.Traffic.GetCameraRequest();
            inValue.AccessCode = AccessCode;
            inValue.CameraID = CameraID;
            return ((Wsdot.Traffic.IHighwayCameras)(this)).GetCameraAsync(inValue);
        }
    }
}
