//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelerInfoMapServices.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TravelerInfoMapServices.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;currentVersion&quot;: 10.1,
        ///	&quot;id&quot; : 0,
        ///	&quot;name&quot; : &quot;Grouped Cameras&quot;,
        ///	&quot;type&quot; : &quot;Feature Layer&quot;,
        ///	&quot;description&quot; : &quot;&quot;,
        ///	&quot;copyrightText&quot; : &quot;&quot;,
        ///	&quot;defaultVisibility&quot;: true,
        ///	&quot;relationships&quot; : [],
        ///	&quot;isDataVersioned&quot;: false,
        ///	&quot;supportsRollbackOnFailureParameter&quot;: false,
        ///	&quot;supportsStatistics&quot;: false,
        ///	&quot;supportsAdvancedQueries&quot;:false,
        ///	&quot;geometryType&quot; : &quot;esriGeometryPoint&quot;,
        ///	&quot;minScale&quot; : 0,
        ///	&quot;maxScale&quot; : 0,
        ///	&quot;extent&quot; :  {&quot;xmin&quot;:-125.31005750014883,&quot;ymin&quot;:45.25517031487897,&quot;xmax&quot;:-116.2573231251512,&quot;ymax [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GroupedCamerasLayer {
            get {
                return ResourceManager.GetString("GroupedCamerasLayer", resourceCulture);
            }
        }
    }
}
