//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wsdot.Traffic
{
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Wsdot.Traffic.IHighwayAlerts")]
    public interface IHighwayAlerts
    {
        
        // CODEGEN: Parameter 'GetAlertsResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHighwayAlerts/GetAlerts", ReplyAction="http://tempuri.org/IHighwayAlerts/GetAlertsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Wsdot.Traffic.GetAlertsResponse GetAlerts(Wsdot.Traffic.GetAlertsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHighwayAlerts/GetAlerts", ReplyAction="http://tempuri.org/IHighwayAlerts/GetAlertsResponse")]
        System.Threading.Tasks.Task<Wsdot.Traffic.GetAlertsResponse> GetAlertsAsync(Wsdot.Traffic.GetAlertsRequest request);
        
        // CODEGEN: Parameter 'GetAlertsAsDataSetResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHighwayAlerts/GetAlertsAsDataSet", ReplyAction="http://tempuri.org/IHighwayAlerts/GetAlertsAsDataSetResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Wsdot.Traffic.GetAlertsAsDataSetResponse GetAlertsAsDataSet(Wsdot.Traffic.GetAlertsAsDataSetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHighwayAlerts/GetAlertsAsDataSet", ReplyAction="http://tempuri.org/IHighwayAlerts/GetAlertsAsDataSetResponse")]
        System.Threading.Tasks.Task<Wsdot.Traffic.GetAlertsAsDataSetResponse> GetAlertsAsDataSetAsync(Wsdot.Traffic.GetAlertsAsDataSetRequest request);
        
        // CODEGEN: Parameter 'SearchAlertsResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHighwayAlerts/SearchAlerts", ReplyAction="http://tempuri.org/IHighwayAlerts/SearchAlertsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Wsdot.Traffic.SearchAlertsResponse SearchAlerts(Wsdot.Traffic.SearchAlertsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHighwayAlerts/SearchAlerts", ReplyAction="http://tempuri.org/IHighwayAlerts/SearchAlertsResponse")]
        System.Threading.Tasks.Task<Wsdot.Traffic.SearchAlertsResponse> SearchAlertsAsync(Wsdot.Traffic.SearchAlertsRequest request);
        
        // CODEGEN: Parameter 'GetAlertResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHighwayAlerts/GetAlert", ReplyAction="http://tempuri.org/IHighwayAlerts/GetAlertResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Wsdot.Traffic.GetAlertResponse GetAlert(Wsdot.Traffic.GetAlertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHighwayAlerts/GetAlert", ReplyAction="http://tempuri.org/IHighwayAlerts/GetAlertResponse")]
        System.Threading.Tasks.Task<Wsdot.Traffic.GetAlertResponse> GetAlertAsync(Wsdot.Traffic.GetAlertRequest request);
        
        // CODEGEN: Parameter 'GetEventCategoriesResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHighwayAlerts/GetEventCategories", ReplyAction="http://tempuri.org/IHighwayAlerts/GetEventCategoriesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Wsdot.Traffic.GetEventCategoriesResponse GetEventCategories(Wsdot.Traffic.GetEventCategoriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHighwayAlerts/GetEventCategories", ReplyAction="http://tempuri.org/IHighwayAlerts/GetEventCategoriesResponse")]
        System.Threading.Tasks.Task<Wsdot.Traffic.GetEventCategoriesResponse> GetEventCategoriesAsync(Wsdot.Traffic.GetEventCategoriesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class Alert
    {
        
        private int alertIDField;
        
        private bool alertIDFieldSpecified;
        
        private string countyField;
        
        private RoadwayLocation endRoadwayLocationField;
        
        private System.Nullable<System.DateTime> endTimeField;
        
        private bool endTimeFieldSpecified;
        
        private string eventCategoryField;
        
        private string eventStatusField;
        
        private string extendedDescriptionField;
        
        private string headlineDescriptionField;
        
        private System.Nullable<System.DateTime> lastUpdatedTimeField;
        
        private bool lastUpdatedTimeFieldSpecified;
        
        private string priorityField;
        
        private string regionField;
        
        private RoadwayLocation startRoadwayLocationField;
        
        private System.Nullable<System.DateTime> startTimeField;
        
        private bool startTimeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int AlertID
        {
            get
            {
                return this.alertIDField;
            }
            set
            {
                this.alertIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AlertIDSpecified
        {
            get
            {
                return this.alertIDFieldSpecified;
            }
            set
            {
                this.alertIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string County
        {
            get
            {
                return this.countyField;
            }
            set
            {
                this.countyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public RoadwayLocation EndRoadwayLocation
        {
            get
            {
                return this.endRoadwayLocationField;
            }
            set
            {
                this.endRoadwayLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> EndTime
        {
            get
            {
                return this.endTimeField;
            }
            set
            {
                this.endTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EndTimeSpecified
        {
            get
            {
                return this.endTimeFieldSpecified;
            }
            set
            {
                this.endTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string EventCategory
        {
            get
            {
                return this.eventCategoryField;
            }
            set
            {
                this.eventCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string EventStatus
        {
            get
            {
                return this.eventStatusField;
            }
            set
            {
                this.eventStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string ExtendedDescription
        {
            get
            {
                return this.extendedDescriptionField;
            }
            set
            {
                this.extendedDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string HeadlineDescription
        {
            get
            {
                return this.headlineDescriptionField;
            }
            set
            {
                this.headlineDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<System.DateTime> LastUpdatedTime
        {
            get
            {
                return this.lastUpdatedTimeField;
            }
            set
            {
                this.lastUpdatedTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastUpdatedTimeSpecified
        {
            get
            {
                return this.lastUpdatedTimeFieldSpecified;
            }
            set
            {
                this.lastUpdatedTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string Priority
        {
            get
            {
                return this.priorityField;
            }
            set
            {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string Region
        {
            get
            {
                return this.regionField;
            }
            set
            {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public RoadwayLocation StartRoadwayLocation
        {
            get
            {
                return this.startRoadwayLocationField;
            }
            set
            {
                this.startRoadwayLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<System.DateTime> StartTime
        {
            get
            {
                return this.startTimeField;
            }
            set
            {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartTimeSpecified
        {
            get
            {
                return this.startTimeFieldSpecified;
            }
            set
            {
                this.startTimeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class RoadwayLocation
    {
        
        private string descriptionField;
        
        private string directionField;
        
        private decimal latitudeField;
        
        private bool latitudeFieldSpecified;
        
        private decimal longitudeField;
        
        private bool longitudeFieldSpecified;
        
        private decimal milePostField;
        
        private bool milePostFieldSpecified;
        
        private string roadNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Direction
        {
            get
            {
                return this.directionField;
            }
            set
            {
                this.directionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal Latitude
        {
            get
            {
                return this.latitudeField;
            }
            set
            {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LatitudeSpecified
        {
            get
            {
                return this.latitudeFieldSpecified;
            }
            set
            {
                this.latitudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal Longitude
        {
            get
            {
                return this.longitudeField;
            }
            set
            {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LongitudeSpecified
        {
            get
            {
                return this.longitudeFieldSpecified;
            }
            set
            {
                this.longitudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal MilePost
        {
            get
            {
                return this.milePostField;
            }
            set
            {
                this.milePostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MilePostSpecified
        {
            get
            {
                return this.milePostFieldSpecified;
            }
            set
            {
                this.milePostFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string RoadName
        {
            get
            {
                return this.roadNameField;
            }
            set
            {
                this.roadNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAlerts", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAlertsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AccessCode;
        
        public GetAlertsRequest()
        {
        }
        
        public GetAlertsRequest(string AccessCode)
        {
            this.AccessCode = AccessCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAlertsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAlertsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
        public Wsdot.Traffic.Alert[] GetAlertsResult;
        
        public GetAlertsResponse()
        {
        }
        
        public GetAlertsResponse(Wsdot.Traffic.Alert[] GetAlertsResult)
        {
            this.GetAlertsResult = GetAlertsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAlertsAsDataSet", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAlertsAsDataSetRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AccessCode;
        
        public GetAlertsAsDataSetRequest()
        {
        }
        
        public GetAlertsAsDataSetRequest(string AccessCode)
        {
            this.AccessCode = AccessCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAlertsAsDataSetResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAlertsAsDataSetResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet GetAlertsAsDataSetResult;
        
        public GetAlertsAsDataSetResponse()
        {
        }
        
        public GetAlertsAsDataSetResponse(System.Data.DataSet GetAlertsAsDataSetResult)
        {
            this.GetAlertsAsDataSetResult = GetAlertsAsDataSetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchAlerts", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SearchAlertsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AccessCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StateRoute;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Region;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> SearchTimeStart;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> SearchTimeEnd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> StartingMilepost;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> EndingMilepost;
        
        public SearchAlertsRequest()
        {
        }
        
        public SearchAlertsRequest(string AccessCode, string StateRoute, string Region, System.Nullable<System.DateTime> SearchTimeStart, System.Nullable<System.DateTime> SearchTimeEnd, System.Nullable<decimal> StartingMilepost, System.Nullable<decimal> EndingMilepost)
        {
            this.AccessCode = AccessCode;
            this.StateRoute = StateRoute;
            this.Region = Region;
            this.SearchTimeStart = SearchTimeStart;
            this.SearchTimeEnd = SearchTimeEnd;
            this.StartingMilepost = StartingMilepost;
            this.EndingMilepost = EndingMilepost;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchAlertsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SearchAlertsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
        public Wsdot.Traffic.Alert[] SearchAlertsResult;
        
        public SearchAlertsResponse()
        {
        }
        
        public SearchAlertsResponse(Wsdot.Traffic.Alert[] SearchAlertsResult)
        {
            this.SearchAlertsResult = SearchAlertsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAlert", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAlertRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AccessCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int AlertID;
        
        public GetAlertRequest()
        {
        }
        
        public GetAlertRequest(string AccessCode, int AlertID)
        {
            this.AccessCode = AccessCode;
            this.AlertID = AlertID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAlertResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAlertResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Wsdot.Traffic.Alert GetAlertResult;
        
        public GetAlertResponse()
        {
        }
        
        public GetAlertResponse(Wsdot.Traffic.Alert GetAlertResult)
        {
            this.GetAlertResult = GetAlertResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEventCategories", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetEventCategoriesRequest
    {
        
        public GetEventCategoriesRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEventCategoriesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetEventCategoriesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] GetEventCategoriesResult;
        
        public GetEventCategoriesResponse()
        {
        }
        
        public GetEventCategoriesResponse(string[] GetEventCategoriesResult)
        {
            this.GetEventCategoriesResult = GetEventCategoriesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHighwayAlertsChannel : Wsdot.Traffic.IHighwayAlerts, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HighwayAlertsClient : System.ServiceModel.ClientBase<Wsdot.Traffic.IHighwayAlerts>, Wsdot.Traffic.IHighwayAlerts
    {
        
        public HighwayAlertsClient()
        {
        }
        
        public HighwayAlertsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public HighwayAlertsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public HighwayAlertsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public HighwayAlertsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Wsdot.Traffic.GetAlertsResponse Wsdot.Traffic.IHighwayAlerts.GetAlerts(Wsdot.Traffic.GetAlertsRequest request)
        {
            return base.Channel.GetAlerts(request);
        }
        
        public Wsdot.Traffic.Alert[] GetAlerts(string AccessCode)
        {
            Wsdot.Traffic.GetAlertsRequest inValue = new Wsdot.Traffic.GetAlertsRequest();
            inValue.AccessCode = AccessCode;
            Wsdot.Traffic.GetAlertsResponse retVal = ((Wsdot.Traffic.IHighwayAlerts)(this)).GetAlerts(inValue);
            return retVal.GetAlertsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Wsdot.Traffic.GetAlertsResponse> Wsdot.Traffic.IHighwayAlerts.GetAlertsAsync(Wsdot.Traffic.GetAlertsRequest request)
        {
            return base.Channel.GetAlertsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Wsdot.Traffic.GetAlertsResponse> GetAlertsAsync(string AccessCode)
        {
            Wsdot.Traffic.GetAlertsRequest inValue = new Wsdot.Traffic.GetAlertsRequest();
            inValue.AccessCode = AccessCode;
            return ((Wsdot.Traffic.IHighwayAlerts)(this)).GetAlertsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Wsdot.Traffic.GetAlertsAsDataSetResponse Wsdot.Traffic.IHighwayAlerts.GetAlertsAsDataSet(Wsdot.Traffic.GetAlertsAsDataSetRequest request)
        {
            return base.Channel.GetAlertsAsDataSet(request);
        }
        
        public System.Data.DataSet GetAlertsAsDataSet(string AccessCode)
        {
            Wsdot.Traffic.GetAlertsAsDataSetRequest inValue = new Wsdot.Traffic.GetAlertsAsDataSetRequest();
            inValue.AccessCode = AccessCode;
            Wsdot.Traffic.GetAlertsAsDataSetResponse retVal = ((Wsdot.Traffic.IHighwayAlerts)(this)).GetAlertsAsDataSet(inValue);
            return retVal.GetAlertsAsDataSetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Wsdot.Traffic.GetAlertsAsDataSetResponse> Wsdot.Traffic.IHighwayAlerts.GetAlertsAsDataSetAsync(Wsdot.Traffic.GetAlertsAsDataSetRequest request)
        {
            return base.Channel.GetAlertsAsDataSetAsync(request);
        }
        
        public System.Threading.Tasks.Task<Wsdot.Traffic.GetAlertsAsDataSetResponse> GetAlertsAsDataSetAsync(string AccessCode)
        {
            Wsdot.Traffic.GetAlertsAsDataSetRequest inValue = new Wsdot.Traffic.GetAlertsAsDataSetRequest();
            inValue.AccessCode = AccessCode;
            return ((Wsdot.Traffic.IHighwayAlerts)(this)).GetAlertsAsDataSetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Wsdot.Traffic.SearchAlertsResponse Wsdot.Traffic.IHighwayAlerts.SearchAlerts(Wsdot.Traffic.SearchAlertsRequest request)
        {
            return base.Channel.SearchAlerts(request);
        }
        
        public Wsdot.Traffic.Alert[] SearchAlerts(string AccessCode, string StateRoute, string Region, System.Nullable<System.DateTime> SearchTimeStart, System.Nullable<System.DateTime> SearchTimeEnd, System.Nullable<decimal> StartingMilepost, System.Nullable<decimal> EndingMilepost)
        {
            Wsdot.Traffic.SearchAlertsRequest inValue = new Wsdot.Traffic.SearchAlertsRequest();
            inValue.AccessCode = AccessCode;
            inValue.StateRoute = StateRoute;
            inValue.Region = Region;
            inValue.SearchTimeStart = SearchTimeStart;
            inValue.SearchTimeEnd = SearchTimeEnd;
            inValue.StartingMilepost = StartingMilepost;
            inValue.EndingMilepost = EndingMilepost;
            Wsdot.Traffic.SearchAlertsResponse retVal = ((Wsdot.Traffic.IHighwayAlerts)(this)).SearchAlerts(inValue);
            return retVal.SearchAlertsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Wsdot.Traffic.SearchAlertsResponse> Wsdot.Traffic.IHighwayAlerts.SearchAlertsAsync(Wsdot.Traffic.SearchAlertsRequest request)
        {
            return base.Channel.SearchAlertsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Wsdot.Traffic.SearchAlertsResponse> SearchAlertsAsync(string AccessCode, string StateRoute, string Region, System.Nullable<System.DateTime> SearchTimeStart, System.Nullable<System.DateTime> SearchTimeEnd, System.Nullable<decimal> StartingMilepost, System.Nullable<decimal> EndingMilepost)
        {
            Wsdot.Traffic.SearchAlertsRequest inValue = new Wsdot.Traffic.SearchAlertsRequest();
            inValue.AccessCode = AccessCode;
            inValue.StateRoute = StateRoute;
            inValue.Region = Region;
            inValue.SearchTimeStart = SearchTimeStart;
            inValue.SearchTimeEnd = SearchTimeEnd;
            inValue.StartingMilepost = StartingMilepost;
            inValue.EndingMilepost = EndingMilepost;
            return ((Wsdot.Traffic.IHighwayAlerts)(this)).SearchAlertsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Wsdot.Traffic.GetAlertResponse Wsdot.Traffic.IHighwayAlerts.GetAlert(Wsdot.Traffic.GetAlertRequest request)
        {
            return base.Channel.GetAlert(request);
        }
        
        public Wsdot.Traffic.Alert GetAlert(string AccessCode, int AlertID)
        {
            Wsdot.Traffic.GetAlertRequest inValue = new Wsdot.Traffic.GetAlertRequest();
            inValue.AccessCode = AccessCode;
            inValue.AlertID = AlertID;
            Wsdot.Traffic.GetAlertResponse retVal = ((Wsdot.Traffic.IHighwayAlerts)(this)).GetAlert(inValue);
            return retVal.GetAlertResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Wsdot.Traffic.GetAlertResponse> Wsdot.Traffic.IHighwayAlerts.GetAlertAsync(Wsdot.Traffic.GetAlertRequest request)
        {
            return base.Channel.GetAlertAsync(request);
        }
        
        public System.Threading.Tasks.Task<Wsdot.Traffic.GetAlertResponse> GetAlertAsync(string AccessCode, int AlertID)
        {
            Wsdot.Traffic.GetAlertRequest inValue = new Wsdot.Traffic.GetAlertRequest();
            inValue.AccessCode = AccessCode;
            inValue.AlertID = AlertID;
            return ((Wsdot.Traffic.IHighwayAlerts)(this)).GetAlertAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Wsdot.Traffic.GetEventCategoriesResponse Wsdot.Traffic.IHighwayAlerts.GetEventCategories(Wsdot.Traffic.GetEventCategoriesRequest request)
        {
            return base.Channel.GetEventCategories(request);
        }
        
        public string[] GetEventCategories()
        {
            Wsdot.Traffic.GetEventCategoriesRequest inValue = new Wsdot.Traffic.GetEventCategoriesRequest();
            Wsdot.Traffic.GetEventCategoriesResponse retVal = ((Wsdot.Traffic.IHighwayAlerts)(this)).GetEventCategories(inValue);
            return retVal.GetEventCategoriesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Wsdot.Traffic.GetEventCategoriesResponse> Wsdot.Traffic.IHighwayAlerts.GetEventCategoriesAsync(Wsdot.Traffic.GetEventCategoriesRequest request)
        {
            return base.Channel.GetEventCategoriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Wsdot.Traffic.GetEventCategoriesResponse> GetEventCategoriesAsync()
        {
            Wsdot.Traffic.GetEventCategoriesRequest inValue = new Wsdot.Traffic.GetEventCategoriesRequest();
            return ((Wsdot.Traffic.IHighwayAlerts)(this)).GetEventCategoriesAsync(inValue);
        }
    }
}
