//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wsdot.Traffic
{
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Wsdot.Traffic.ITrafficFlow")]
    public interface ITrafficFlow
    {
        
        // CODEGEN: Parameter 'GetTrafficFlowsResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrafficFlow/GetTrafficFlows", ReplyAction="http://tempuri.org/ITrafficFlow/GetTrafficFlowsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Wsdot.Traffic.GetTrafficFlowsResponse GetTrafficFlows(Wsdot.Traffic.GetTrafficFlowsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrafficFlow/GetTrafficFlows", ReplyAction="http://tempuri.org/ITrafficFlow/GetTrafficFlowsResponse")]
        System.Threading.Tasks.Task<Wsdot.Traffic.GetTrafficFlowsResponse> GetTrafficFlowsAsync(Wsdot.Traffic.GetTrafficFlowsRequest request);
        
        // CODEGEN: Parameter 'GetTrafficFlowsAsDataSetResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrafficFlow/GetTrafficFlowsAsDataSet", ReplyAction="http://tempuri.org/ITrafficFlow/GetTrafficFlowsAsDataSetResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Wsdot.Traffic.GetTrafficFlowsAsDataSetResponse GetTrafficFlowsAsDataSet(Wsdot.Traffic.GetTrafficFlowsAsDataSetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrafficFlow/GetTrafficFlowsAsDataSet", ReplyAction="http://tempuri.org/ITrafficFlow/GetTrafficFlowsAsDataSetResponse")]
        System.Threading.Tasks.Task<Wsdot.Traffic.GetTrafficFlowsAsDataSetResponse> GetTrafficFlowsAsDataSetAsync(Wsdot.Traffic.GetTrafficFlowsAsDataSetRequest request);
        
        // CODEGEN: Parameter 'SearchTrafficFlowsResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrafficFlow/SearchTrafficFlows", ReplyAction="http://tempuri.org/ITrafficFlow/SearchTrafficFlowsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Wsdot.Traffic.SearchTrafficFlowsResponse SearchTrafficFlows(Wsdot.Traffic.SearchTrafficFlowsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrafficFlow/SearchTrafficFlows", ReplyAction="http://tempuri.org/ITrafficFlow/SearchTrafficFlowsResponse")]
        System.Threading.Tasks.Task<Wsdot.Traffic.SearchTrafficFlowsResponse> SearchTrafficFlowsAsync(Wsdot.Traffic.SearchTrafficFlowsRequest request);
        
        // CODEGEN: Parameter 'GetTrafficFlowResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrafficFlow/GetTrafficFlow", ReplyAction="http://tempuri.org/ITrafficFlow/GetTrafficFlowResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Wsdot.Traffic.GetTrafficFlowResponse GetTrafficFlow(Wsdot.Traffic.GetTrafficFlowRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrafficFlow/GetTrafficFlow", ReplyAction="http://tempuri.org/ITrafficFlow/GetTrafficFlowResponse")]
        System.Threading.Tasks.Task<Wsdot.Traffic.GetTrafficFlowResponse> GetTrafficFlowAsync(Wsdot.Traffic.GetTrafficFlowRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class FlowData
    {
        
        private int flowDataIDField;
        
        private bool flowDataIDFieldSpecified;
        
        private FlowStationReading flowReadingValueField;
        
        private bool flowReadingValueFieldSpecified;
        
        private RoadwayLocation flowStationLocationField;
        
        private string regionField;
        
        private string stationNameField;
        
        private System.DateTime timeField;
        
        private bool timeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int FlowDataID
        {
            get
            {
                return this.flowDataIDField;
            }
            set
            {
                this.flowDataIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FlowDataIDSpecified
        {
            get
            {
                return this.flowDataIDFieldSpecified;
            }
            set
            {
                this.flowDataIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public FlowStationReading FlowReadingValue
        {
            get
            {
                return this.flowReadingValueField;
            }
            set
            {
                this.flowReadingValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FlowReadingValueSpecified
        {
            get
            {
                return this.flowReadingValueFieldSpecified;
            }
            set
            {
                this.flowReadingValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public RoadwayLocation FlowStationLocation
        {
            get
            {
                return this.flowStationLocationField;
            }
            set
            {
                this.flowStationLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Region
        {
            get
            {
                return this.regionField;
            }
            set
            {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string StationName
        {
            get
            {
                return this.stationNameField;
            }
            set
            {
                this.stationNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime Time
        {
            get
            {
                return this.timeField;
            }
            set
            {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TimeSpecified
        {
            get
            {
                return this.timeFieldSpecified;
            }
            set
            {
                this.timeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public enum FlowStationReading
    {
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        WideOpen,
        
        /// <remarks/>
        Moderate,
        
        /// <remarks/>
        Heavy,
        
        /// <remarks/>
        StopAndGo,
        
        /// <remarks/>
        NoData,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class RoadwayLocation
    {
        
        private string descriptionField;
        
        private string directionField;
        
        private decimal latitudeField;
        
        private bool latitudeFieldSpecified;
        
        private decimal longitudeField;
        
        private bool longitudeFieldSpecified;
        
        private decimal milePostField;
        
        private bool milePostFieldSpecified;
        
        private string roadNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Direction
        {
            get
            {
                return this.directionField;
            }
            set
            {
                this.directionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal Latitude
        {
            get
            {
                return this.latitudeField;
            }
            set
            {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LatitudeSpecified
        {
            get
            {
                return this.latitudeFieldSpecified;
            }
            set
            {
                this.latitudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal Longitude
        {
            get
            {
                return this.longitudeField;
            }
            set
            {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LongitudeSpecified
        {
            get
            {
                return this.longitudeFieldSpecified;
            }
            set
            {
                this.longitudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal MilePost
        {
            get
            {
                return this.milePostField;
            }
            set
            {
                this.milePostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MilePostSpecified
        {
            get
            {
                return this.milePostFieldSpecified;
            }
            set
            {
                this.milePostFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string RoadName
        {
            get
            {
                return this.roadNameField;
            }
            set
            {
                this.roadNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTrafficFlows", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTrafficFlowsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AccessCode;
        
        public GetTrafficFlowsRequest()
        {
        }
        
        public GetTrafficFlowsRequest(string AccessCode)
        {
            this.AccessCode = AccessCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTrafficFlowsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTrafficFlowsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
        public Wsdot.Traffic.FlowData[] GetTrafficFlowsResult;
        
        public GetTrafficFlowsResponse()
        {
        }
        
        public GetTrafficFlowsResponse(Wsdot.Traffic.FlowData[] GetTrafficFlowsResult)
        {
            this.GetTrafficFlowsResult = GetTrafficFlowsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTrafficFlowsAsDataSet", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTrafficFlowsAsDataSetRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AccessCode;
        
        public GetTrafficFlowsAsDataSetRequest()
        {
        }
        
        public GetTrafficFlowsAsDataSetRequest(string AccessCode)
        {
            this.AccessCode = AccessCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTrafficFlowsAsDataSetResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTrafficFlowsAsDataSetResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet GetTrafficFlowsAsDataSetResult;
        
        public GetTrafficFlowsAsDataSetResponse()
        {
        }
        
        public GetTrafficFlowsAsDataSetResponse(System.Data.DataSet GetTrafficFlowsAsDataSetResult)
        {
            this.GetTrafficFlowsAsDataSetResult = GetTrafficFlowsAsDataSetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchTrafficFlows", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SearchTrafficFlowsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AccessCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StateRoute;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Region;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> SearchStartTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> SearchEndTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> StartingMilepost;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> EndingMilepost;
        
        public SearchTrafficFlowsRequest()
        {
        }
        
        public SearchTrafficFlowsRequest(string AccessCode, string StateRoute, string Region, System.Nullable<System.DateTime> SearchStartTime, System.Nullable<System.DateTime> SearchEndTime, System.Nullable<double> StartingMilepost, System.Nullable<double> EndingMilepost)
        {
            this.AccessCode = AccessCode;
            this.StateRoute = StateRoute;
            this.Region = Region;
            this.SearchStartTime = SearchStartTime;
            this.SearchEndTime = SearchEndTime;
            this.StartingMilepost = StartingMilepost;
            this.EndingMilepost = EndingMilepost;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchTrafficFlowsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SearchTrafficFlowsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
        public Wsdot.Traffic.FlowData[] SearchTrafficFlowsResult;
        
        public SearchTrafficFlowsResponse()
        {
        }
        
        public SearchTrafficFlowsResponse(Wsdot.Traffic.FlowData[] SearchTrafficFlowsResult)
        {
            this.SearchTrafficFlowsResult = SearchTrafficFlowsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTrafficFlow", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTrafficFlowRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AccessCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int FlowDataID;
        
        public GetTrafficFlowRequest()
        {
        }
        
        public GetTrafficFlowRequest(string AccessCode, int FlowDataID)
        {
            this.AccessCode = AccessCode;
            this.FlowDataID = FlowDataID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTrafficFlowResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTrafficFlowResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Wsdot.Traffic.FlowData GetTrafficFlowResult;
        
        public GetTrafficFlowResponse()
        {
        }
        
        public GetTrafficFlowResponse(Wsdot.Traffic.FlowData GetTrafficFlowResult)
        {
            this.GetTrafficFlowResult = GetTrafficFlowResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrafficFlowChannel : Wsdot.Traffic.ITrafficFlow, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrafficFlowClient : System.ServiceModel.ClientBase<Wsdot.Traffic.ITrafficFlow>, Wsdot.Traffic.ITrafficFlow
    {
        
        public TrafficFlowClient()
        {
        }
        
        public TrafficFlowClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public TrafficFlowClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public TrafficFlowClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public TrafficFlowClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Wsdot.Traffic.GetTrafficFlowsResponse Wsdot.Traffic.ITrafficFlow.GetTrafficFlows(Wsdot.Traffic.GetTrafficFlowsRequest request)
        {
            return base.Channel.GetTrafficFlows(request);
        }
        
        public Wsdot.Traffic.FlowData[] GetTrafficFlows(string AccessCode)
        {
            Wsdot.Traffic.GetTrafficFlowsRequest inValue = new Wsdot.Traffic.GetTrafficFlowsRequest();
            inValue.AccessCode = AccessCode;
            Wsdot.Traffic.GetTrafficFlowsResponse retVal = ((Wsdot.Traffic.ITrafficFlow)(this)).GetTrafficFlows(inValue);
            return retVal.GetTrafficFlowsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Wsdot.Traffic.GetTrafficFlowsResponse> Wsdot.Traffic.ITrafficFlow.GetTrafficFlowsAsync(Wsdot.Traffic.GetTrafficFlowsRequest request)
        {
            return base.Channel.GetTrafficFlowsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Wsdot.Traffic.GetTrafficFlowsResponse> GetTrafficFlowsAsync(string AccessCode)
        {
            Wsdot.Traffic.GetTrafficFlowsRequest inValue = new Wsdot.Traffic.GetTrafficFlowsRequest();
            inValue.AccessCode = AccessCode;
            return ((Wsdot.Traffic.ITrafficFlow)(this)).GetTrafficFlowsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Wsdot.Traffic.GetTrafficFlowsAsDataSetResponse Wsdot.Traffic.ITrafficFlow.GetTrafficFlowsAsDataSet(Wsdot.Traffic.GetTrafficFlowsAsDataSetRequest request)
        {
            return base.Channel.GetTrafficFlowsAsDataSet(request);
        }
        
        public System.Data.DataSet GetTrafficFlowsAsDataSet(string AccessCode)
        {
            Wsdot.Traffic.GetTrafficFlowsAsDataSetRequest inValue = new Wsdot.Traffic.GetTrafficFlowsAsDataSetRequest();
            inValue.AccessCode = AccessCode;
            Wsdot.Traffic.GetTrafficFlowsAsDataSetResponse retVal = ((Wsdot.Traffic.ITrafficFlow)(this)).GetTrafficFlowsAsDataSet(inValue);
            return retVal.GetTrafficFlowsAsDataSetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Wsdot.Traffic.GetTrafficFlowsAsDataSetResponse> Wsdot.Traffic.ITrafficFlow.GetTrafficFlowsAsDataSetAsync(Wsdot.Traffic.GetTrafficFlowsAsDataSetRequest request)
        {
            return base.Channel.GetTrafficFlowsAsDataSetAsync(request);
        }
        
        public System.Threading.Tasks.Task<Wsdot.Traffic.GetTrafficFlowsAsDataSetResponse> GetTrafficFlowsAsDataSetAsync(string AccessCode)
        {
            Wsdot.Traffic.GetTrafficFlowsAsDataSetRequest inValue = new Wsdot.Traffic.GetTrafficFlowsAsDataSetRequest();
            inValue.AccessCode = AccessCode;
            return ((Wsdot.Traffic.ITrafficFlow)(this)).GetTrafficFlowsAsDataSetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Wsdot.Traffic.SearchTrafficFlowsResponse Wsdot.Traffic.ITrafficFlow.SearchTrafficFlows(Wsdot.Traffic.SearchTrafficFlowsRequest request)
        {
            return base.Channel.SearchTrafficFlows(request);
        }
        
        public Wsdot.Traffic.FlowData[] SearchTrafficFlows(string AccessCode, string StateRoute, string Region, System.Nullable<System.DateTime> SearchStartTime, System.Nullable<System.DateTime> SearchEndTime, System.Nullable<double> StartingMilepost, System.Nullable<double> EndingMilepost)
        {
            Wsdot.Traffic.SearchTrafficFlowsRequest inValue = new Wsdot.Traffic.SearchTrafficFlowsRequest();
            inValue.AccessCode = AccessCode;
            inValue.StateRoute = StateRoute;
            inValue.Region = Region;
            inValue.SearchStartTime = SearchStartTime;
            inValue.SearchEndTime = SearchEndTime;
            inValue.StartingMilepost = StartingMilepost;
            inValue.EndingMilepost = EndingMilepost;
            Wsdot.Traffic.SearchTrafficFlowsResponse retVal = ((Wsdot.Traffic.ITrafficFlow)(this)).SearchTrafficFlows(inValue);
            return retVal.SearchTrafficFlowsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Wsdot.Traffic.SearchTrafficFlowsResponse> Wsdot.Traffic.ITrafficFlow.SearchTrafficFlowsAsync(Wsdot.Traffic.SearchTrafficFlowsRequest request)
        {
            return base.Channel.SearchTrafficFlowsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Wsdot.Traffic.SearchTrafficFlowsResponse> SearchTrafficFlowsAsync(string AccessCode, string StateRoute, string Region, System.Nullable<System.DateTime> SearchStartTime, System.Nullable<System.DateTime> SearchEndTime, System.Nullable<double> StartingMilepost, System.Nullable<double> EndingMilepost)
        {
            Wsdot.Traffic.SearchTrafficFlowsRequest inValue = new Wsdot.Traffic.SearchTrafficFlowsRequest();
            inValue.AccessCode = AccessCode;
            inValue.StateRoute = StateRoute;
            inValue.Region = Region;
            inValue.SearchStartTime = SearchStartTime;
            inValue.SearchEndTime = SearchEndTime;
            inValue.StartingMilepost = StartingMilepost;
            inValue.EndingMilepost = EndingMilepost;
            return ((Wsdot.Traffic.ITrafficFlow)(this)).SearchTrafficFlowsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Wsdot.Traffic.GetTrafficFlowResponse Wsdot.Traffic.ITrafficFlow.GetTrafficFlow(Wsdot.Traffic.GetTrafficFlowRequest request)
        {
            return base.Channel.GetTrafficFlow(request);
        }
        
        public Wsdot.Traffic.FlowData GetTrafficFlow(string AccessCode, int FlowDataID)
        {
            Wsdot.Traffic.GetTrafficFlowRequest inValue = new Wsdot.Traffic.GetTrafficFlowRequest();
            inValue.AccessCode = AccessCode;
            inValue.FlowDataID = FlowDataID;
            Wsdot.Traffic.GetTrafficFlowResponse retVal = ((Wsdot.Traffic.ITrafficFlow)(this)).GetTrafficFlow(inValue);
            return retVal.GetTrafficFlowResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Wsdot.Traffic.GetTrafficFlowResponse> Wsdot.Traffic.ITrafficFlow.GetTrafficFlowAsync(Wsdot.Traffic.GetTrafficFlowRequest request)
        {
            return base.Channel.GetTrafficFlowAsync(request);
        }
        
        public System.Threading.Tasks.Task<Wsdot.Traffic.GetTrafficFlowResponse> GetTrafficFlowAsync(string AccessCode, int FlowDataID)
        {
            Wsdot.Traffic.GetTrafficFlowRequest inValue = new Wsdot.Traffic.GetTrafficFlowRequest();
            inValue.AccessCode = AccessCode;
            inValue.FlowDataID = FlowDataID;
            return ((Wsdot.Traffic.ITrafficFlow)(this)).GetTrafficFlowAsync(inValue);
        }
    }
}
