//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wsdot.Traffic
{
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Wsdot.Traffic.ITravelTimes")]
    public interface ITravelTimes
    {
        
        // CODEGEN: Parameter 'GetTravelTimesResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITravelTimes/GetTravelTimes", ReplyAction="http://tempuri.org/ITravelTimes/GetTravelTimesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Wsdot.Traffic.GetTravelTimesResponse GetTravelTimes(Wsdot.Traffic.GetTravelTimesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITravelTimes/GetTravelTimes", ReplyAction="http://tempuri.org/ITravelTimes/GetTravelTimesResponse")]
        System.Threading.Tasks.Task<Wsdot.Traffic.GetTravelTimesResponse> GetTravelTimesAsync(Wsdot.Traffic.GetTravelTimesRequest request);
        
        // CODEGEN: Parameter 'GetTravelTimeResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITravelTimes/GetTravelTime", ReplyAction="http://tempuri.org/ITravelTimes/GetTravelTimeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Wsdot.Traffic.GetTravelTimeResponse GetTravelTime(Wsdot.Traffic.GetTravelTimeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITravelTimes/GetTravelTime", ReplyAction="http://tempuri.org/ITravelTimes/GetTravelTimeResponse")]
        System.Threading.Tasks.Task<Wsdot.Traffic.GetTravelTimeResponse> GetTravelTimeAsync(Wsdot.Traffic.GetTravelTimeRequest request);
        
        // CODEGEN: Parameter 'GetTravelTimesAsDataSetResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITravelTimes/GetTravelTimesAsDataSet", ReplyAction="http://tempuri.org/ITravelTimes/GetTravelTimesAsDataSetResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Wsdot.Traffic.GetTravelTimesAsDataSetResponse GetTravelTimesAsDataSet(Wsdot.Traffic.GetTravelTimesAsDataSetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITravelTimes/GetTravelTimesAsDataSet", ReplyAction="http://tempuri.org/ITravelTimes/GetTravelTimesAsDataSetResponse")]
        System.Threading.Tasks.Task<Wsdot.Traffic.GetTravelTimesAsDataSetResponse> GetTravelTimesAsDataSetAsync(Wsdot.Traffic.GetTravelTimesAsDataSetRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class TravelTimeRoute
    {
        
        private int averageTimeField;
        
        private bool averageTimeFieldSpecified;
        
        private int currentTimeField;
        
        private bool currentTimeFieldSpecified;
        
        private string descriptionField;
        
        private decimal distanceField;
        
        private bool distanceFieldSpecified;
        
        private RoadwayLocation endPointField;
        
        private string nameField;
        
        private RoadwayLocation startPointField;
        
        private System.DateTime timeUpdatedField;
        
        private bool timeUpdatedFieldSpecified;
        
        private int travelTimeIDField;
        
        private bool travelTimeIDFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int AverageTime
        {
            get
            {
                return this.averageTimeField;
            }
            set
            {
                this.averageTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AverageTimeSpecified
        {
            get
            {
                return this.averageTimeFieldSpecified;
            }
            set
            {
                this.averageTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int CurrentTime
        {
            get
            {
                return this.currentTimeField;
            }
            set
            {
                this.currentTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CurrentTimeSpecified
        {
            get
            {
                return this.currentTimeFieldSpecified;
            }
            set
            {
                this.currentTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal Distance
        {
            get
            {
                return this.distanceField;
            }
            set
            {
                this.distanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DistanceSpecified
        {
            get
            {
                return this.distanceFieldSpecified;
            }
            set
            {
                this.distanceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public RoadwayLocation EndPoint
        {
            get
            {
                return this.endPointField;
            }
            set
            {
                this.endPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public RoadwayLocation StartPoint
        {
            get
            {
                return this.startPointField;
            }
            set
            {
                this.startPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime TimeUpdated
        {
            get
            {
                return this.timeUpdatedField;
            }
            set
            {
                this.timeUpdatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TimeUpdatedSpecified
        {
            get
            {
                return this.timeUpdatedFieldSpecified;
            }
            set
            {
                this.timeUpdatedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int TravelTimeID
        {
            get
            {
                return this.travelTimeIDField;
            }
            set
            {
                this.travelTimeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TravelTimeIDSpecified
        {
            get
            {
                return this.travelTimeIDFieldSpecified;
            }
            set
            {
                this.travelTimeIDFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class RoadwayLocation
    {
        
        private string descriptionField;
        
        private string directionField;
        
        private decimal latitudeField;
        
        private bool latitudeFieldSpecified;
        
        private decimal longitudeField;
        
        private bool longitudeFieldSpecified;
        
        private decimal milePostField;
        
        private bool milePostFieldSpecified;
        
        private string roadNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Direction
        {
            get
            {
                return this.directionField;
            }
            set
            {
                this.directionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal Latitude
        {
            get
            {
                return this.latitudeField;
            }
            set
            {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LatitudeSpecified
        {
            get
            {
                return this.latitudeFieldSpecified;
            }
            set
            {
                this.latitudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal Longitude
        {
            get
            {
                return this.longitudeField;
            }
            set
            {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LongitudeSpecified
        {
            get
            {
                return this.longitudeFieldSpecified;
            }
            set
            {
                this.longitudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal MilePost
        {
            get
            {
                return this.milePostField;
            }
            set
            {
                this.milePostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MilePostSpecified
        {
            get
            {
                return this.milePostFieldSpecified;
            }
            set
            {
                this.milePostFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string RoadName
        {
            get
            {
                return this.roadNameField;
            }
            set
            {
                this.roadNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTravelTimes", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTravelTimesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AccessCode;
        
        public GetTravelTimesRequest()
        {
        }
        
        public GetTravelTimesRequest(string AccessCode)
        {
            this.AccessCode = AccessCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTravelTimesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTravelTimesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
        public Wsdot.Traffic.TravelTimeRoute[] GetTravelTimesResult;
        
        public GetTravelTimesResponse()
        {
        }
        
        public GetTravelTimesResponse(Wsdot.Traffic.TravelTimeRoute[] GetTravelTimesResult)
        {
            this.GetTravelTimesResult = GetTravelTimesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTravelTime", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTravelTimeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AccessCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int TravelTimeID;
        
        public GetTravelTimeRequest()
        {
        }
        
        public GetTravelTimeRequest(string AccessCode, int TravelTimeID)
        {
            this.AccessCode = AccessCode;
            this.TravelTimeID = TravelTimeID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTravelTimeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTravelTimeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Wsdot.Traffic.TravelTimeRoute GetTravelTimeResult;
        
        public GetTravelTimeResponse()
        {
        }
        
        public GetTravelTimeResponse(Wsdot.Traffic.TravelTimeRoute GetTravelTimeResult)
        {
            this.GetTravelTimeResult = GetTravelTimeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTravelTimesAsDataSet", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTravelTimesAsDataSetRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AccessCode;
        
        public GetTravelTimesAsDataSetRequest()
        {
        }
        
        public GetTravelTimesAsDataSetRequest(string AccessCode)
        {
            this.AccessCode = AccessCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTravelTimesAsDataSetResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTravelTimesAsDataSetResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet GetTravelTimesAsDataSetResult;
        
        public GetTravelTimesAsDataSetResponse()
        {
        }
        
        public GetTravelTimesAsDataSetResponse(System.Data.DataSet GetTravelTimesAsDataSetResult)
        {
            this.GetTravelTimesAsDataSetResult = GetTravelTimesAsDataSetResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITravelTimesChannel : Wsdot.Traffic.ITravelTimes, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TravelTimesClient : System.ServiceModel.ClientBase<Wsdot.Traffic.ITravelTimes>, Wsdot.Traffic.ITravelTimes
    {
        
        public TravelTimesClient()
        {
        }
        
        public TravelTimesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public TravelTimesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public TravelTimesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public TravelTimesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Wsdot.Traffic.GetTravelTimesResponse Wsdot.Traffic.ITravelTimes.GetTravelTimes(Wsdot.Traffic.GetTravelTimesRequest request)
        {
            return base.Channel.GetTravelTimes(request);
        }
        
        public Wsdot.Traffic.TravelTimeRoute[] GetTravelTimes(string AccessCode)
        {
            Wsdot.Traffic.GetTravelTimesRequest inValue = new Wsdot.Traffic.GetTravelTimesRequest();
            inValue.AccessCode = AccessCode;
            Wsdot.Traffic.GetTravelTimesResponse retVal = ((Wsdot.Traffic.ITravelTimes)(this)).GetTravelTimes(inValue);
            return retVal.GetTravelTimesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Wsdot.Traffic.GetTravelTimesResponse> Wsdot.Traffic.ITravelTimes.GetTravelTimesAsync(Wsdot.Traffic.GetTravelTimesRequest request)
        {
            return base.Channel.GetTravelTimesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Wsdot.Traffic.GetTravelTimesResponse> GetTravelTimesAsync(string AccessCode)
        {
            Wsdot.Traffic.GetTravelTimesRequest inValue = new Wsdot.Traffic.GetTravelTimesRequest();
            inValue.AccessCode = AccessCode;
            return ((Wsdot.Traffic.ITravelTimes)(this)).GetTravelTimesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Wsdot.Traffic.GetTravelTimeResponse Wsdot.Traffic.ITravelTimes.GetTravelTime(Wsdot.Traffic.GetTravelTimeRequest request)
        {
            return base.Channel.GetTravelTime(request);
        }
        
        public Wsdot.Traffic.TravelTimeRoute GetTravelTime(string AccessCode, int TravelTimeID)
        {
            Wsdot.Traffic.GetTravelTimeRequest inValue = new Wsdot.Traffic.GetTravelTimeRequest();
            inValue.AccessCode = AccessCode;
            inValue.TravelTimeID = TravelTimeID;
            Wsdot.Traffic.GetTravelTimeResponse retVal = ((Wsdot.Traffic.ITravelTimes)(this)).GetTravelTime(inValue);
            return retVal.GetTravelTimeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Wsdot.Traffic.GetTravelTimeResponse> Wsdot.Traffic.ITravelTimes.GetTravelTimeAsync(Wsdot.Traffic.GetTravelTimeRequest request)
        {
            return base.Channel.GetTravelTimeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Wsdot.Traffic.GetTravelTimeResponse> GetTravelTimeAsync(string AccessCode, int TravelTimeID)
        {
            Wsdot.Traffic.GetTravelTimeRequest inValue = new Wsdot.Traffic.GetTravelTimeRequest();
            inValue.AccessCode = AccessCode;
            inValue.TravelTimeID = TravelTimeID;
            return ((Wsdot.Traffic.ITravelTimes)(this)).GetTravelTimeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Wsdot.Traffic.GetTravelTimesAsDataSetResponse Wsdot.Traffic.ITravelTimes.GetTravelTimesAsDataSet(Wsdot.Traffic.GetTravelTimesAsDataSetRequest request)
        {
            return base.Channel.GetTravelTimesAsDataSet(request);
        }
        
        public System.Data.DataSet GetTravelTimesAsDataSet(string AccessCode)
        {
            Wsdot.Traffic.GetTravelTimesAsDataSetRequest inValue = new Wsdot.Traffic.GetTravelTimesAsDataSetRequest();
            inValue.AccessCode = AccessCode;
            Wsdot.Traffic.GetTravelTimesAsDataSetResponse retVal = ((Wsdot.Traffic.ITravelTimes)(this)).GetTravelTimesAsDataSet(inValue);
            return retVal.GetTravelTimesAsDataSetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Wsdot.Traffic.GetTravelTimesAsDataSetResponse> Wsdot.Traffic.ITravelTimes.GetTravelTimesAsDataSetAsync(Wsdot.Traffic.GetTravelTimesAsDataSetRequest request)
        {
            return base.Channel.GetTravelTimesAsDataSetAsync(request);
        }
        
        public System.Threading.Tasks.Task<Wsdot.Traffic.GetTravelTimesAsDataSetResponse> GetTravelTimesAsDataSetAsync(string AccessCode)
        {
            Wsdot.Traffic.GetTravelTimesAsDataSetRequest inValue = new Wsdot.Traffic.GetTravelTimesAsDataSetRequest();
            inValue.AccessCode = AccessCode;
            return ((Wsdot.Traffic.ITravelTimes)(this)).GetTravelTimesAsDataSetAsync(inValue);
        }
    }
}
